name: 'test'
seed: 2024
steps: 100
save_freq: 10
env_name: 'mnist'
optimizer: ['sgd','svrg','gssgd','gssvrg','gssvrg_tau']
layers: [32]
lr: 0.01
num_sgd: 1
inner_svrg_num_sgd: 1
num_mc_fsigma: 1
inner_svrg_iterations: 10
s: 1.
sgd_lr: 0.005
svrg_lr: 0.025
gssgd_lr: 0.001
gssvrg_lr: 0.001
gssvrg_tau_lr: 0.005